defaults:
  - hydra_default
  - _self_

llama_family: 
  - meta-llama/Llama-2-13b-chat-hf
  - meta-llama/Llama-3.2-1B-Instruct
  - meta-llama/Llama-3.1-8B-Instruct
  - meta-llama/Llama-3.3-70B-Instruct

gemma_family:
  - google/gemma-1.1-7b-it
  - google/gemma-2-2b-it
  - google/gemma-2-9b-it
  - google/gemma-2-27b-it

qwen_family:
  - Qwen/Qwen2-7B-Instruct
  - Qwen/Qwen2.5-32B-Instruct
  - Qwen/Qwen3-0.6B
  - Qwen/Qwen3-4B-Thinking-2507

gpt_family:
  - openai/gpt-oss-20b

refusal_family:
  - /scratch/refusal-unlearning/refusal_gemma1.1_7b
  - /scratch/refusal-unlearning/refusal_gemma2_2b
  - /scratch/refusal-unlearning/refusal_gemma2_9b
  - /scratch/refusal-unlearning/refusal_gemma2_27b
  - /scratch/refusal-unlearning/refusal_llama2_13b
  - /scratch/refusal-unlearning/refusal_llama3.1_8b
  - /scratch/refusal-unlearning/refusal_llama3.2_1b
  - /scratch/refusal-unlearning/refusal_qwen2_7b
  - /scratch/refusal-unlearning/refusal_qwen3_0.6b
  - /scratch/refusal-unlearning/refusal_qwen3_4b_think
  - /scratch/refusal-unlearning/refusal_qwen2.5_32b
  - /scratch/refusal-unlearning/refusal_llama3.3_70b
  - /scratch/refusal-unlearning/refusal_gpt-oss_20b 
